### ISSUE TITLE
`import 'ts2php/types/php';` 报错

### ISSUE THREAD

**Issue by l5oo00** [searchfe/san-ssr#17]
```bash
Error: Cannot find module 'ts2php/types/php'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at path (/project_root/node_modules/san-ssr/dist/loaders/common-js.js:46:24)
    at eval (eval at require (/project_root/node_modules/san-ssr/dist/loaders/common-js.js:38:24), <anonymous>:9:1)
    at CommonJS.require (/project_root/node_modules/san-ssr/dist/loaders/common-js.js:39:13)
    at path (/project_root/node_modules/san-ssr/dist/loaders/common-js.js:43:33)
    at eval (eval at require (/project_root/node_modules/san-ssr/dist/loaders/common-js.js:38:24), <anonymous>:12:17)
    at CommonJS.require (/project_root/node_modules/san-ssr/dist/loaders/common-js.js:39:13)
```

实际应该引入的是 `ts2php/types/php.d.ts`

**Comment by harttle** [comment]
是因为不存在对应的 ts2php/types/php.js 导致的，目前的 ssr 机制下，编译模板到语法树需要组件的 JavaScript 可以执行。提供一个模块名到模块内容的配置到就可以了，因此和 https://github.com/searchfe/san-ssr/issues/12 重复。
