### ISSUE TITLE
import 外部 ts 文件报错

### ISSUE THREAD

**Issue by l5oo00** [searchfe/san-ssr#4]
san 组件的 ts 文件里引用依赖的工具包 ts 文件， 报错 `Error: Cannot find module 'xxx'`, 示例代码如下：

```ts
// app/components/demo.san.ts
import {Component} from 'san';
import {
    versionCompare
} from '../lib/utils';
export default class DemoComponent extends Component {
    static computed = {
        isOk() {
            return versionCompare('10.0', '9.0') >= 0;
        }
    }
    static template = `<div>
        {{ isOk ? 'san-ssr import bug.' : ''}}
    </div>`;
}


// app/lib/utils.ts
export function versionCompare(a, b) {
    return parseInt(a, 10) - parseInt(b, 10);
}
```

报错如下：
```bash
Error: Cannot find module '../lib/utils'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at path (/projectRoot/node_modules/san-ssr/dist/loaders/common-js.js:35:24)
    at eval (eval at require (/projectRoot/node_modules/san-ssr/dist/loaders/common-js.js:29:24), <anonymous>:10:17)
    at CommonJS.require (/projectRoot/node_modules/san-ssr/dist/loaders/common-js.js:30:13)
    at ToJSCompiler.evalComponentClass (/projectRoot/node_modules/san-ssr/dist/compilers/to-js-compiler.js:62:25)
    at ToPHPCompiler.compileFromTS (/projectRoot/node_modules/san-ssr/dist/compilers/to-php-compiler.js:50:50)
    at ToPHPCompiler.compile (/projectRoot/node_modules/san-ssr/dist/compilers/to-php-compiler.js:39:25)
```

**Comment by l5oo00** [comment]
将 utils 放到和 san.ts 平级的目录下， 就没有问题了

**Comment by l5oo00** [comment]
还有个问题： 模板字符串的反引号（`）没有被转换为引号， 编译产出的 php 文件如下：

```php
    class DemoComponent extends Component {
        public static $computed;
        public static $template = `<div>\\n        {{ isOk ? 'san-ssr import bug.' : ''}}\\n    </div>`;
    }
```

**Comment by harttle** [comment]
模板字符串语法是 ts2php 的问题，参见： https://github.com/searchfe/san-ssr/issues/4#issuecomment-547762406

**Comment by l5oo00** [comment]
template 使用模板字符串并包含变量后， 会导致编译产出在 PHP 运行时报错， 和 @harttle  讨论后将所有 static 属性后置。
